eclipse/microprofile-reactive-streams-operators

- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/CompletionBuilder.java
- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/InternalStages.java
- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/ProcessorBuilder.java
- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/PublisherBuilder.java
- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/ReactiveStreams.java
- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/ReactiveStreamsGraphBuilder.java
- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/SubscriberBuilder.java
This superclass didn't actually provide any public functionality, it was just an implementation convenience, and therefore introduced confusion in the API. Instead, a private ReactiveStreamsGraphBuilder class is introduced that implements its functionality, and each public API build has one of these, and works with these.
The removal of this was discussed in the MicroProfile hangout, and also in issue #6.
> Remove the abstract ReactiveStreamsBuilder superclass

- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/ProcessorBuilder.java
- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/PublisherBuilder.java
- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/spi/Stage.java
- streams/tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/PeekStageVerification.java
This PR fixes #17.
It adds a peek stage corresponding to the `peek` operation from the `java.util.Streams`.
> Add the peek stage.

- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/ProcessorBuilder.java
- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/PublisherBuilder.java
- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/spi/Stage.java
- streams/tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/FlatMapPublisherStageVerification.java
- streams/tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/ReactiveStreamsTck.java
Fixes #49 
* This new stage is an adaptation of the flatMap stage but the mapper function returns a Publisher instead of a PublisherBuilder.
* The tests are derived from the flatMap verification test suite
> Introduce a flatMapPublisher method

- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/CompletionRunner.java
- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/PublisherBuilder.java
- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/package-info.java
- streams/spec/src/main/asciidoc/architecture.asciidoc
- streams/tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/FilterStageVerification.java
This change has been discussed during the MP Reactive call (July 3rd) and is related to #16.
In addition to the code change, the spec has been updated.
> Rename CompletionBuilder to CompletionRunner

- streams/spec/src/main/asciidoc/java-streams.asciidoc
- streams/spec/src/main/asciidoc/microprofile-reactive-streams-operators-spec.asciidoc
Related to #51.
Add a section defining the similarities and differences with the Java Stream API.
> Add a section in the spec about the similarities and differences with Java Stream

- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/ProcessorBuilder.java
- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/PublisherBuilder.java
- streams/tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/CollectStageVerification.java
As discussed in #51, define a variant of the collect method accepting a supplier and a bi-consumer. Because of Reactive Streams, the combiner is not used and so not part of the signature
> Add a variant of the `collect` method

- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/ProcessorBuilder.java
- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/PublisherBuilder.java
Fix typos in the javadoc of the `peek` stage.
> Fix typos in the peek stage javadoc and signature

- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/PublisherBuilder.java
#56 was developed before the renaming from CompletionBuilder to CompletionRunner (#58). As a consequence, the compilation fails. This PR fixes it.
> Fix build after the merge of the `collect` stage

- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/CompletionRunner.java
- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/GraphAccessor.java
- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/ProcessorBuilder.java
- streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/SubscriberBuilder.java
- streams/tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/GraphAccessorVerification.java
- streams/tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/ReactiveStreamsTck.java
- streams/tck/src/test/java/org/eclipse/microprofile/reactive/streams/tck/TckTest.java
We use this in Lightbend's MicroProfile Messaging implementation, it gives a way to build, for example, a `Flow` from a `ProcessorBuilder`, without having to build a `Processor`.
Note that all the `toGraph` methods are package private, so never appear in the user API, so this remains strictly an implementation detail except for the `GraphAccessor` class. It would have been nice to put that in the `spi` package, but unfortunately then it wouldn't be able to access the package private `toGraph` methods.
> Added method for accessing the graph directly

- streams/README.adoc
Fixes #77.
Also removed the Lightbend RxJava implementation link since it's been deleted (SmallRye now provides an RxJava implementation).
> Add SmallRye implementation to streams README

- streams/spec/src/main/asciidoc/microprofile-reactive-streams-operators-spec.asciidoc
- streams/spec/src/main/asciidoc/tck.asciidoc
Technically this PR depends on #84, since it documents the changes introduced there, so it should be merged until that is merged in case anything changes before then.
> Added documentation for the TCK to the specification

- streams/pom.xml
- streams/tck-arquillian/pom.xml
- streams/tck-arquillian/src/main/java/org/eclipse/microprofile/reactive/streams/tck/arquillian/ReactiveStreamsArquillianTck.java
- streams/tck-arquillian/src/main/java/org/eclipse/microprofile/reactive/streams/tck/arquillian/ReactiveStreamsCdiTck.java
- streams/tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/spi/OnErrorResumeStageVerification.java
This provides a test class that can be run in Arquillian. I have tested this with Thorntail (using an Arquillian `AuxillaryArchiveAppender` to add in my own implementation), and it works.
I did originally try and make this work better with Arquillian, by trying to have it deploy each test to the container. I was able to work around the fact that the tests are created by a factory by writing my own custom container `TestRunner` that gets them from the factory. I was able to work around the fact that none of the tests extend the TestNG `Arquillian` class by extracting all its logic into a TestNG listener that was applied to the whole suite. And finally, I was able to work around the fact that none of the test classes has an `@Deployment` annotated method on it, by writing a custom …
> Added support for running the TCK in Arquillian

- api/src/main/java/org/eclipse/microprofile/reactive/streams/ProcessorBuilder.java
- api/src/main/java/org/eclipse/microprofile/reactive/streams/PublisherBuilder.java
- api/src/main/java/org/eclipse/microprofile/reactive/streams/ReactiveStreams.java
- api/src/main/java/org/eclipse/microprofile/reactive/streams/spi/Stage.java
- spec/src/main/asciidoc/architecture.asciidoc
- spec/src/main/asciidoc/cdi.asciidoc
- spec/src/main/asciidoc/design.asciidoc
- spec/src/main/asciidoc/implementation.asciidoc
- spec/src/main/asciidoc/microprofile-reactive-streams-operators-spec.asciidoc
- tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/api/ReactiveStreamsVerification.java
- tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/spi/FlatMapCompletionStageVerification.java
- tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/spi/FlatMapIterableStageVerification.java
- tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/spi/MapStageVerification.java
- tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/spi/OfStageVerification.java
* Split a design section out from the architecture section
* Added an implementation section for notes on how things should be implemented, includes requirements on how errors should be handled and propgated, memory visibility requirements, null handling requirements.
* Added a section on CDI. There is one requirement here, that is that if a MicroProfile container provides an implementation of this spec, it must make an engine available by injection. Additionally, added advice about how context may be specified by other specs.
* Filled out the javadocs for each stage to include all the requirements that the TCK tests for, so now they can be implemented without needing to run the TCK to learn out how things should be handled.
* Added a small number of TCK tests, testing for null elements …
> More work on the streams spec

- README.adoc
There were a number of markdown style links which I've fixed to be valid asciidoc links.
> Fixed links in README

- api/src/main/java/org/eclipse/microprofile/reactive/streams/operators/spi/ReactiveStreamsFactoryResolver.java
- core/src/main/java/org/eclipse/microprofile/reactive/streams/operators/core/ReactiveStreamsEngineResolver.java
It is up to the ClassLoader to do parent delegation,
we should not be second guessing it by attempting to
manually delegate to the parent.
Signed-off-by: Stuart Douglas <stuart.w.douglas@gmail.com>
> Remove broken ClassLoader delegation

- api/src/main/java/org/eclipse/microprofile/reactive/streams/operators/package-info.java
- api/src/main/java/org/eclipse/microprofile/reactive/streams/operators/spi/package-info.java
The package line in these files did not match the package they were
actually in, resulting in the package javadoc being missing from the
output.
Fixes #145
> Fix package-info package line

- pom.xml
- tck/pom.xml
* Switch from the CDI dependency from javax to jakarta
* Fixes #128
* Exclude the EL and EJB transitive dependencies pulled in the CDI API
* Fixes #123 
* Make OSGi dependency provided scope
* Fixes #132
> Dependency updates

- tck/src/main/java/org/eclipse/microprofile/reactive/streams/operators/tck/api/SubscriberBuilderVerification.java
Avoid assuming that SubscriberBuilder.build() returns a `DefaultCompletionSubscriber`
Fixes #141
> Don't assume DefaultCompletionSubscriber

- api/src/main/java/org/eclipse/microprofile/reactive/streams/operators/CompletionSubscriber.java
Make clear that the returned object is not going to handle completing the `CompletionStage` for you.
Fixes #129
> Improve doc for CompletionSubscriber.of

- api/src/main/java/org/eclipse/microprofile/reactive/streams/operators/ProcessorBuilder.java
- api/src/main/java/org/eclipse/microprofile/reactive/streams/operators/PublisherBuilder.java
This is already implied by the fact that each method which returns a
PublisherBuilder or ProcessorBuilder states that it returns a new
instance, but it's helpful to be explicit in the class javadoc.
Fixes #142
> Clarify that Builders are immutable

- .gitignore
- api/pom.xml
- api/src/main/java/org/eclipse/microprofile/reactive/streams/operators/ConnectingOperators.java
- api/src/main/java/org/eclipse/microprofile/reactive/streams/operators/ProcessorBuilder.java
- api/src/main/java/org/eclipse/microprofile/reactive/streams/operators/PublisherBuilder.java
- api/src/main/java/org/eclipse/microprofile/reactive/streams/operators/package-info.java
- pom.xml
- tck/pom.xml
- tck/src/main/java/org/eclipse/microprofile/reactive/streams/operators/tck/arquillian/ReactiveStreamsArquillianTck.java
The main aim of this PR is to update the version of `microprofile-parent` to 2.8. This also has the effect of updating the version of TestNG to 7.5.1. The Arquillian runner `ReactiveStreamsArquillianTck` was using some TestNG internals which have now been moved. So instead of using internals, we have changed to using just APIs.
The version of the `frontend-maven-plugin` has also been updated to one which works on an M1 Mac.
Rebuilding with the new microprofile-parent version has also resulted in some minor changes to javadoc in a couple of API classes.
> Update microprofile-parent version

- .gitignore
- tck/src/main/java/org/eclipse/microprofile/reactive/streams/operators/tck/ReactiveStreamsTck.java
When running in an Jakarta EE web/full profile environment, the ScheduleExecutorService should be provided by the container.
> Allow the ScheduledExecutorService to be provided by the container
