eclipse/microprofile-reactive-streams-operators

approach.asciidoc
This is an import of the following document:
https://docs.google.com/document/d/1PEVm6viY4fR7fQyC6i-O-PSO2ciBMCdO9b2R3bsLAnk/edit#
I've incorporated most of the feedback into this.
=> Import MicroProfile Approach to Reactive doc

streams/spec/src/main/asciidoc/architecture.asciidoc, streams/spec/src/main/asciidoc/examples.asciidoc, streams/spec/src/main/asciidoc/microprofile-reactive-streams-spec.asciidoc
This PR proposes some small fixes in the stream specification. Larger tasks will be handled in separated PRs.
=> Small fixes / rewording in the stream specification

approach.asciidoc
Also, restructure the Flow vs. Reactive Stream section
=> Small fixes and rewording

streams/README.adoc, streams/spec/src/main/asciidoc/architecture.asciidoc, streams/spec/src/main/asciidoc/examples.asciidoc
Some small wording fixes as suggested by @venkats.
=> Small fixes

README.md, approach.asciidoc, streams/api/pom.xml, streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/package-info.java, streams/pom.xml, streams/spec/pom.xml, streams/spec/src/main/asciidoc/microprofile-reactive-streams-operators-spec.asciidoc, streams/tck/pom.xml
=> Renamed to MicroProfile Reactive Streams Operators

streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/CompletionSubscriber.java
=> Make CompletionSubscriber#of public

streams/tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/ReactiveStreamsTck.java
=> Add the PeekStageVerification to the test suite

messaging/api/pom.xml
Signed-off-by: Emily Jiang <emijiang@uk.ibm.com>
=> fix build break

streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/ProcessorBuilder.java, streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/PublisherBuilder.java, streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/spi/Stage.java, streams/tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/DistinctStageVerification.java, streams/tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/ReactiveStreamsTck.java
Define a `distinct` stage as discussed in #51.
=> Define a `distinct` stage

streams/tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/FlatMapPublisherStageVerification.java, streams/tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/FlatMapStageVerification.java, streams/tck/src/main/java/org/eclipse/microprofile/reactive/streams/tck/ScheduledPublisher.java
Remove the ScheduledPublisher as duplicated code and make a class package protected.
=> Remove the ScheduledPublisher as duplicated code

tck-arquillian/src/main/java/org/eclipse/microprofile/reactive/streams/tck/arquillian/ReactiveStreamsArquillianTck.java
=> Add Reactive Streams examples to Arquillian

api/src/main/java/org/eclipse/microprofile/reactive/streams/ReactiveStreams.java, api/src/main/java/org/eclipse/microprofile/reactive/streams/ReactiveStreamsFactoryResolver.java, core/src/main/java/org/eclipse/microprofile/reactive/streams/core/CompletionRunnerImpl.java, core/src/main/java/org/eclipse/microprofile/reactive/streams/core/ProcessorBuilderImpl.java, core/src/main/java/org/eclipse/microprofile/reactive/streams/core/PublisherBuilderImpl.java, core/src/main/java/org/eclipse/microprofile/reactive/streams/core/ReactiveStreamsEngineResolver.java, core/src/main/java/org/eclipse/microprofile/reactive/streams/core/ReactiveStreamsGraphBuilder.java, core/src/main/java/org/eclipse/microprofile/reactive/streams/core/SubscriberBuilderImpl.java
Use the same approach as the config specification for the 2 SPIs used by the spec.
=> Fix #103 - Change how SPI are loaded to support OSGi

api/src/main/java/org/eclipse/microprofile/reactive/streams/ReactiveStreamsFactoryResolver.java, core/src/main/java/org/eclipse/microprofile/reactive/streams/core/ReactiveStreamsEngineResolver.java
Forgot to replace this reference, my bad.
=> Fix wrong class name in exception message

api/package.json, pom.xml, site.yaml
* Update the SCM URL in the `pom.xml` file and the marble diagram generation
* Update the site.yaml
=> Update the Git Repo URL

api/pom.xml, core/pom.xml, pom.xml, spec/pom.xml, tck/pom.xml
Signed-off-by: Emily Jiang <emijiang@uk.ibm.com>
=> Revert a bad release and start a new one

pom.xml
=> Update reactive streams version to 1.0.3

pom.xml
Signed-off-by: Gordon Hutchison <Gordon.Hutchison@gmail.com>
Fixes #143
=> Refresh maven javadoc plugin to 3.2 to fix build issue

.github/ISSUE_TEMPLATE/01-compatible-certification-request.md, api/pom.xml, api/src/main/javadoc/licenses/Draft/license.html, api/src/main/javadoc/licenses/Final/license.html, api/src/main/resources/META-INF/LICENSE, api/src/main/resources/META-INF/placeholder.txt, pom.xml, spec/pom.xml, spec/src/main/asciidoc/license-efsl.adoc, spec/src/main/asciidoc/microprofile-reactive-streams-operators-spec.asciidoc, tck/pom.xml, tck/src/main/licenses/Draft/LICENSE, tck/src/main/licenses/Final/LICENSE.md
=> Prepare for releases under working group

tck/README.adoc
=> Add a README with the instructions to run the TCK

.gitignore, pom.xml, tck/pom.xml
=> package running instructions in the tck jar

pom.xml
Fix gpg issue: Signing failed: not a tty
=> fix gpg issue

api/src/main/java/org/eclipse/microprofile/reactive/streams/operators/PublisherBuilder.java
=> Fixes #137 buildRs(RSE) clarification

api/src/main/java/org/eclipse/microprofile/reactive/streams/operators/TransformingOperators.java, api/src/main/java/org/eclipse/microprofile/reactive/streams/operators/spi/Stage.java
=> Fix: #135 clarify the javadoc on flatMapCompletionStage

tck/README.adoc
=> prep 2.0 release

api/src/main/java/org/eclipse/microprofile/reactive/streams/operators/spi/ReactiveStreamsFactoryResolver.java, core/src/main/java/org/eclipse/microprofile/reactive/streams/operators/core/ReactiveStreamsEngineResolver.java, spec/src/main/asciidoc/release_notes.asciidoc
Without this when running with a security manager I get exceptions in WildFly
=> ServiceLoader.load() should be in a privileged action
